app/models.py
# -*- coding: utf-8 -*-

from app import db, app

from Crypto.Cipher import AES
import base64

secret_key = app.config['SECRET_KEY']
cipher = AES.new(secret_key, AES.MODE_ECB)

class Base(db.Model):
    __abstract__ = True
    uuid = db.Column(db.String(32), primary_key=True)
    create_time = db.Column(db.DateTime)
    update_time = db.Column(db.DateTime)

class Host(Base):
    __tablename__ = 'host'
    name = db.Column(db.String(40), index=True)
    ip = db.Column(db.String(15))
    port = db.Column(db.String(5))
    password_hash = db.Column(db.String(128))
    status = db.Column(db.Integer, default=0)
    group_id = db.Column(db.Integer)
    last_check_time = db.Column(db.DateTime)

    @property
    def password(self):
        return cipher.decrypt(base64.b64decode(self.password_hash)).strip().decode()

    @password.setter
    def password(self, password):
        self.password_hash = base64.b64encode(cipher.encrypt(password.rjust(32)))

app/__init__.py
# -*- coding: utf-8 -*-

from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object('config')

db = SQLAlchemy(app)

from app.admin import bp as admin_bp
app.register_blueprint(admin_bp, url_prefix='/admin')

app/admin/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

bp = Blueprint('admin', __name__)

from app.admin.views import *
from app.admin.api import *

app/admin/views.py
# -*- coding: utf-8 -*-

from flask import request, render_template, redirect, url_for
from app.admin import bp
from app.models import Host


@bp.route('/', methods=['GET'])
def index():
    return render_template('admin/index.html')

@bp.route('/dashboard/<id>', methods=['GET'])
def dashboard(id=1):
    return render_template('admin/dashboard.html', id=id)

@bp.route('/host', methods=['GET'])
def host():
    return render_template('admin/host.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
	<meta charset="utf-8">
	<title>性能图</title>
	<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	<link href="/static/custom.css" rel="stylesheet">
	<script src="/static/jquery.min.js"></script>
	<script src="/static/bootstrap/js/bootstrap.min.js"></script>
</head>

<body>
	<nav class="navbar navbar-inverse navbar-static-top">
		<div class="container-fluid">
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li>
						<a href="/admin"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</a>
					</li>
					<!--li>
						<a href="{{ url_for('admin.host') }}">服务器</a>
					</li-->
				</ul>
			</div>
		</div>
	</nav>

	<!-- page content -->
	{% block page_content %}{% endblock %}
	<!-- /page content -->

</body>

</html>